apiVersion: apps/v1
kind: Deployment
metadata:
  name: akstest1
  labels:
    app: akstest1
spec:
  replicas: 1
  template:
    metadata:
      name: akstest1
      labels:
        app: akstest1
    spec: 
      containers:
      - name: your-acr
        image: <your-acr>.azurecr.io/<your-image>:<imageversion>
      imagePullSecrets:
      - name: acs-secret1
        resources:
          limits:
            cpu: 1
            memory: 800m
          requests:
            cpu: .1
            memory: 300m
          ports:
            - containerPort: 8080
      nodeSelector:
        beta.kubernetes.io/os: windows
  selector:
    matchLabels:
      app: akstest1
---
apiVersion: v1
kind: Service
metadata:
  name: akstest1
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: akstest1